// <auto-generated />
using System;
using DeviceDesk.Modules.Phase3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceDesk.netcore.Migrations.Phase3Db
{
    [DbContext(typeof(Phase3DbContext))]
    [Migration("20251202065659_AddPhase3DispatchTablesForExport")]
    partial class AddPhase3DispatchTablesForExport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.BatchDevice", b =>
                {
                    b.Property<Guid>("BatchDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AddedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScannedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ScannedInAudit")
                        .HasColumnType("bit");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("BatchDeviceId");

                    b.HasIndex("BatchId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Serial");

                    b.ToTable("Phase3_BatchDevices", (string)null);
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ArrivedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("AuditCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AuditCompletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AuditPassed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DebriefCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DebriefCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DebriefCompletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DebriefNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeliveryNoteDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryNoteNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DriverName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DriverUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmisCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("EnRoute")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("EnRouteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EnRouteByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionPhotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasExceptions")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("PODDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PODNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SchoolSignatoryName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("SchoolSigned")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("SchoolSignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SignedPODDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TripReference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VehicleReg")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("BatchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PODNumber")
                        .IsUnique()
                        .HasFilter("[PODNumber] IS NOT NULL");

                    b.HasIndex("SchoolName");

                    b.HasIndex("Status");

                    b.ToTable("Phase3_DispatchBatches", (string)null);
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchPOD", b =>
                {
                    b.Property<Guid>("PODId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("DeliveryNoteDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryNoteNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EmisCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ExceptionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionPhotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasExceptions")
                        .HasColumnType("bit");

                    b.Property<long?>("PODDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PODNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SchoolSignatoryName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("SchoolSigned")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("SchoolSignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SignedPODDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SignedPODUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SignedPODUploadedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PODId");

                    b.HasIndex("PODNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TripId");

                    b.ToTable("Phase3_DispatchPODs", (string)null);
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchTrip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DebriefingByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DebriefingCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DebriefingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DebriefingPassed")
                        .HasColumnType("bit");

                    b.Property<bool>("DriverAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DriverAcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DriverUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("FinalSignOffAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FinalSignOffByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FinalSignOffNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FinalSignOffPassed")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TripRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("TripId");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TripRef")
                        .IsUnique();

                    b.ToTable("Phase3_DispatchTrips", (string)null);
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.LoadingAuditScan", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AuditPassed")
                        .HasColumnType("bit");

                    b.Property<string>("AuditedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("int");

                    b.Property<string>("MismatchDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("int");

                    b.Property<string>("ScannedSerials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AuditId");

                    b.HasIndex("BatchId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Phase3_LoadingAuditScans", (string)null);
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.BatchDevice", b =>
                {
                    b.HasOne("DeviceDesk.Modules.Phase3.Models.DispatchBatch", "Batch")
                        .WithMany("Devices")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchPOD", b =>
                {
                    b.HasOne("DeviceDesk.Modules.Phase3.Models.DispatchTrip", "Trip")
                        .WithMany("PODs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.LoadingAuditScan", b =>
                {
                    b.HasOne("DeviceDesk.Modules.Phase3.Models.DispatchBatch", "Batch")
                        .WithMany("AuditScans")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchBatch", b =>
                {
                    b.Navigation("AuditScans");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("DeviceDesk.Modules.Phase3.Models.DispatchTrip", b =>
                {
                    b.Navigation("PODs");
                });
#pragma warning restore 612, 618
        }
    }
}
